apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.name | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    github.com/project-slug: https://github.com/dhanu0001/software-templates1/blob/main/scaffolder-templates/docs-template-cookiecutter/skeleton/catalog-info.yaml
spec:
  type: documentation
  lifecycle: experimental
  owner: {{cookiecutter.owner | jsonify}}
